[github_app]
pr_commands = [
   "/describe",
    "/compliance",
    "/improve",
    "/review",
]

[pr_reviewer] # /review #
# enable/disable features
require_estimate_effort_to_review=false
enable_review_labels_effort=true
extra_instructions="""\
Please review this Pull Request using the following checklist:

- **Error Handling:**  
  Ensure methods handle possible errors or invalid inputs.  
  ✅ Success: Inputs are validated or wrapped in try-catch blocks.  
  ❌ Failure: Methods assume inputs are always valid or can cause exceptions.

- **Code Duplication:**  
  Detect and report duplicated or repeated logic across classes, methods, or files.  
  ✅ Success: Shared logic is extracted into reusable methods or services.  
  ❌ Failure: Similar or identical code blocks appear in multiple places without reuse.
"""