[github_app]
pr_commands = [
   "/describe",
    "/compliance",
    "/improve",
    "/review",
]

[pr_reviewer] # /review #
# enable/disable features
require_estimate_effort_to_review=true
enable_review_labels_effort=false


[rag_arguments]
enable_rag=true